### ISSUE TITLE
onsavedinstancestate restoreinstancestate issue

### ISSUE THREAD

**Issue by AhmedX6** [vlsi/compactmap#8] opened 2022-06-04 00:00 UTC
Hello,

when storing large map onSavedInstanceState it crashes with TransactionTooLargeException.

Do you have any solution ?

**Comment by vlsi** [comment] 2022-06-04 04:27
Could you clarify/provide steps to reproduce?

**Comment by AhmedX6** [comment] 2022-06-04 22:35
Hello,

![image](https://user-images.githubusercontent.com/13573148/172027415-6bd840f8-8cf7-446c-bdee-640966f2cecc.png)

Here I this crash:

!!! FAILED BINDER TRANSACTION !!!  (parcel size = 45086448)

I have a large amount of data on this map. Is it possible to compress it ?

**Comment by vlsi** [comment] 2023-12-13 13:31
I guess it is a duplicate of https://github.com/vlsi/compactmap/issues/9, and it should probably be resolved in 2.0.1

**Closed by vlsi** 2023-12-13 13:31 UTC
